spring:
  cache:
    type: simple
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  data:
    redis:
      host: localhost
      port: 6379
  
  session:
    store-type: none

openai:
  api-key: test-key

compliance:
  rules:
    autoload: false

logging:
  level:
    com.legalai: DEBUG

